{
 "title": "StoreOfCoins - Runtime & Resources",
 "tags": [
  "storeofcoins",
  "runtime",
  "resources"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Service", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "CPU seconds (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(process_cpu_time_seconds_total{job=~\"$job\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Working Set (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (job) (process_memory_usage_bytes{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": ".NET GC Heap Size (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (job) (process_runtime_dotnet_gc_heap_size_bytes{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Collections/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(process_runtime_dotnet_gc_collections_count_total{job=~\"$job\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Thread Pool Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (job) (process_runtime_dotnet_thread_pool_threads_count{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Process Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (job) (process_thread_count{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}